name: simple_csv

source:
  type: filestore
  filepath: data/input.csv
  format: csv

transform:
  steps: []

destination:
  type: filestore
  filepath: s3://my-bucket/output/data.csv
  format: csv
  region: us-east-1
  write_mode: overwrite

runtime:
  batch_size: 5000

