name: test_credentials

source:
  type: postgres
  host: "{{ env_var('SOURCE_HOST') }}"
  port: 5432
  database: "{{ var('SOURCE_DB') }}"
  user: "{{ env_var('SOURCE_USER') }}"
  password: "{{ env_var('SOURCE_PASSWORD') }}"
  table: public.test_table

transform:
  steps: []

destination:
  type: redshift
  host: "{{ env_var('DEST_HOST') }}"
  database: "{{ var('DEST_DB') }}"
  user: "{{ env_var('DEST_USER') }}"
  password: "{{ env_var('DEST_PASSWORD') }}"
  table: dw.test_table
  write_mode: append

runtime:
  batch_size: 5000

